import glob

####
# import the environment
####
Import('env TOOLPATH build_dir')
env = env.Clone()
env.Tool('libraw', toolpath=TOOLPATH)

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to ease building it later
####
lib = env.SharedLibrary('%s/RAWPhotoImporter' % build_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('RAWPhotoImporter', libInstall)

####
# return the plug-in library
####
Return("libInstall")
