BINDEST = $(BINDIR)
PROG = ppmwthresh

INCLIST = -I../lib

MAKETYPE = OPTIMIZED

LIBS = \
	../lib/libwvlt.a


CFLAGS_DEBUG_HP = -g
CFLAGS_DEBUG_IBM = -g
# on (our) SGIs:
#   "make" isn't smart enough, so use "gmake"
#   gcc considers "-g" an "invalid option"
#   the "-O" bypasses an unknown error: "nop must be inside .set noreorder
#     section"
CFLAGS_DEBUG_SGI = -g
CFLAGS_DEBUG_SUN4 = -g -O
CFLAGS_DEBUG = $(CFLAGS_DEBUG_$(ARCH))
CFLAGS_OPTIMIZED = -O -DNDEBUG
CFLAGS_PROFILE = -pg -O -DNDEBUG
CFLAGS = $(CFLAGS_$(MAKETYPE)) $(INCLIST) -DARCH_$(ARCH) -DLIBARRAY_NOT_INSTALLED -DOSREL_MAJOR=$(OSREL_MAJOR)

LD = $(CC)

LDFLAGS_DEBUG = -g
LDFLAGS_OPTIMIZED =
LDFLAGS_PROFILE = -pg
LDFLAGS=$(LDFLAGS_$(MAKETYPE))

LIBFLAGS = -lm

LINTFLAGS = -buchxz

EXTCCSRCS = \
	$(HOME)/src/lib/util/*.c

EXTHDRS = \
	../lib/lintok.h \
	../lib/util.h \
	../lib/wvlt.h

HDRS = \
	local.h

LINT=lint
LINTFLAGS = -bchxz $(INCLIST)

PR = srclist

SRCS = \
	main.c \
	img.c

OBJS = \
	main.o \
	img.o

EXTOBJS = 

default: $(PROG)

backup: Makefile $(SRCS) $(HDRS) ccenter.project
	-mkdir backup
	/bin/cp Makefile $(SRCS) $(HDRS) ccenter.project backup

ccheck:	$(SRCS)
	ccheck $(INCLIST) $(SRCS)

checkin:
	ci -l Makefile $(HDRS) $(SRCS)

clean:
	rm -f a.out core *% $(PROG) $(PROG).pure *_pure_200.o *.pure.* $(OBJS) Makefile.BAK \#*~

install:	$(BINDEST)/$(PROG)

$(BINDEST)/$(PROG):	$(PROG)
	cp $(PROG) $(BINDEST)/$(PROG)

lint:	$(SRCS)
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)

list:	$(HDRS) $(SRCS)
	@$(PR) $(HDRS) $(SRCS)

rcsupdate:
	ci -l Makefile $(SRCS) $(HDRS)

tags:	$(SRCS) $(HDRS)
	ctags -t $(SRCS) $(HDRS) >tags

$(OBJS): $(HDRS) $(EXTHDRS)

$(PROG): $(OBJS) $(LIBS)
	@echo $(LD) $(LDFLAGS) -o $(PROG) $(OBJS) $(EXTOBJS) $(LIBS) $(LIBFLAGS)
	@if $(LD) $(LDFLAGS) -o $(PROG) $(OBJS) $(EXTOBJS) $(LIBS) $(LIBFLAGS) ;\
	then \
		echo $(PROG) linked ;\
	else \
		echo errors in link, $(PROG) executable removed ;\
		/bin/rm $(PROG) ;\
	fi

$(PROG).pure: $(OBJS) $(LIBS)
	@echo purify $(LD) $(LDFLAGS) -o $(PROG).pure $(OBJS) $(EXTOBJS) $(LIBS) $(LIBFLAGS)
	@if purify $(LD) $(LDFLAGS) -o $(PROG).pure $(OBJS) $(EXTOBJS) $(LIBS) $(LIBFLAGS);\
	then \
		echo $(PROG).pure linked ;\
	else \
		echo errors in link, $(PROG).pure executable removed ;\
		/bin/rm $(PROG).pure ;\
	fi

test:
	$(CC) $(CFLAGS_DEBUG) $(INCLIST) -DARCH_$(ARCH) -DLIBARRAY_NOT_INSTALLED -DOSREL_MAJOR=$(OSREL_MAJOR) -DTEST $(SRC) -o `basename $(SRC) .c`_t $(LIBS)

profile:
	$(MAKE) MAKETYPE=PROFILE LIBDIR=$(LIBROOT)/profile PROG=$(PROG)_p
